#!/usr/bin/env perl

my $argv = $ARGV[0];

sub install_docker_image {
  system(
    'docker', 'run',
    '--rm',
    '--user', 'nobody',
    '--entrypoint', 'mailbimi',
    'marcbradshaw/bimivalidator:latest', '--version',
  );
}

sub remove_docker_image {
	system('docker', 'image', 'rm', 'marcbradshaw/bimivalidator:latest');
}

sub install_systemd_service {
  install_docker_image();

  my $payload = '[Unit]
Description=BIMI Validator service
After=network.target

[Service]
Type=simple
ExecStart=docker run --name bimivalidator --rm -p 5000:5000 --user nobody marcbradshaw/bimivalidator:latest
Restart=on-failure

[Install]
WantedBy=multi-user.target';

  open my $outf, '>', '/etc/systemd/system/bimivalidator.service' || die 'could not write service file';
  print $outf $payload;
  close $outf;

	system('systemctl', 'daemon-reload');
	system('systemctl', 'enable', 'bimivalidator.service');
	system('systemctl', 'start',  'bimivalidator.service');
}

sub update_docker_image {
  remove_docker_image();
  install_docker_image();
}

sub update_systemd_service {
  die "Existing service not detected" unless -e '/etc/systemd/system/bimivalidator.service';
	system('systemctl', 'stop',  'bimivalidator.service');
  update_docker_image();
  install_systemd_service();
}

sub main {
  die "This script installs system services, please re-run as root" unless $< == 0;
  die "Docker not detected, please install docker first" if `which docker` eq '';

  # useful aliases
  $argv = 'systemd_install' if $argv eq 'install';
  $argv = 'systemd_update'  if $argv eq 'update';

  return install_systemd_service() if $argv eq 'systemd_install';
  return update_systemd_service()  if $argv eq 'systemd_update';
  return install_docker_image()    if $argv eq 'install_docker_image';
  return update_docker_image()     if $argv eq 'update_docker_image';

  print "BIMI Validator helper script\n";
  print "\n";
  print "1) Install BIMI Validator as a systemd service\n";
  print "2) Update existing BIMI Validator service\n";
  print "\n";
  print "0) exit\n";
  print "\n";

  my $input = <STDIN>;
  chomp $input;

  exit 0 if $input eq '0';
  return install_systemd_service() if $input eq '1';
  return update_systemd_service()  if $input eq '2';

  print "Unknown option $input\n";
  exit 1;
}

main();